name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, msvc]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      uses: actions/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: brew install cmake

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compiler }}++

    - name: Build the project
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
